name: Sync

on: workflow_dispatch

jobs:
  sync:
    name: Sync from swsnr/picture-of-the-day
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: "curl -sSfL https://codeberg.org/swsnr/picture-of-the-day/raw/branch/main/flatpak/de.swsnr.pictureoftheday.yaml > de.swsnr.pictureoftheday.yaml"
      - run: "curl -sSfL https://codeberg.org/swsnr/picture-of-the-day/raw/branch/main/flatpak/de.swsnr.pictureoftheday.cargo-sources.json > de.swsnr.pictureoftheday.cargo-sources.json"
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update from swsnr/picture-of-the-day"
          branch: swsnr/picture-of-the-day/update
          delete-branch: true
          base: master
          sign-commits: true
          title: Update manifest from upstream
          body: |
            Update flatpak manifest from [swsnr/picture-of-the-day](https://codeberg.org/swsnr/picture-of-the-day).

            PR created by [sync workflow](https://github.com/flathub/de.swsnr.pictureoftheday/actions/workflows/sync.yaml)
          assignees: swsnr
